### PR TITLE
Tentatively got selective stickiness working

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
Does not collect tags, but has a whole data structure for to efficiently get stickiness relations, made to be built from tags.

### CODE REVIEW

**Comment by williambl** [comment]
Thanks :D , I'll take a look at this.

Btw, your git config seems to be messed up - the commit says it's by BuildTools, not you.

**Comment by supersaiyansubtlety** [comment]
Oh, wonder if that's something to do with Intellij...
Thanks for pointing that out.

**Comment by williambl** [comment]
@supersaiyansubtlety I've amended your commit so it shows up as being authored by you. It seems like your git config had been modified by the Spigot BuildTools system.

**Comment by supersaiyansubtlety** [comment]
Thanks, I've since fixed my git config

**Comment by supersaiyansubtlety** [comment]
By the way, I see your 'Replace IterableHashSet and IterableBlockTagMap' commit, just thought I'd let you know that since I made the PR I've learned more about the data structures available in the libraries already included by minecraft+fabric, and based on the name of your new data structure, `com.google.common.collect.LinkedHashMultimap` may be a good fit.

**Comment by williambl** [comment]
> based on the name of your new data structure, `com.google.common.collect.LinkedHashMultimap` may be a good fit
~@supersaiyansubtlety 

The data structure I'm using is the `com.google.common.collect.HashMultimap` :) I think the only difference between that and the `Linked...` version is that `LinkedHashMultimap` retains the order that things are added, which doesn't seem too useful for this.

Google's Guava adds *so many* different data structures with quite subtle differences like that, haha.

**Comment by supersaiyansubtlety** [comment]
The other difference is that it's actually meant for iterating over, and the iteration is more efficient. Not sure if you need that though. 

Anyways, glad to see the feature's being worked on again : )

**Pull request merged**
